# Permalinks
permalink:   /:year-:month-"day/:title

# Setup
title: Jo-Hyejin
paginate: 5
baseurl: ''
url: "https://Jo-Hyejin.github.io"

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# Build Settings
markdown: kramdown

# About
author:
name:    Hyejin Jo
email:  jo0920hyejin@gmail.com

# Gems -> plugins
plugins:
  - jekyll-paginate
